[theme]
primaryColor = "#00d09c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#1a1a1a"
font = "sans serif"

[server]
maxUploadSize = 1
enableCORS = false
fileWatcherType = "poll"
